name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with: 
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black flake8 mypy

    - name: Lint with flake8
      run: |
        echo "Running flake8..."
        flake8 . --exclude venv,tests,__pycache__ --max-line-length=100

    - name: Format check with black
      run: |
        echo "Checking code formatting with black..."
        black . --check

    - name: Type checking with mypy
      run: |
        echo "Running mypy..."
        mypy . --ignore-missing-imports
